name: Webapp API Test CI

on:
  pull_request:
    branches:
      - main

jobs:
  api-test:
    name: Setup WebApp and Run Tests
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DEV_DB_NAME: ${{ vars.DEV_DB_NAME }}
      TEST_DB_NAME: ${{ vars.TEST_DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASSWORD: ${{ vars.DB_PASSWORD }}
      APP_GROUP: ${{ vars.APP_GROUP }}
      APP_USER: ${{ vars.APP_USER }}
      ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the repo
        run: |
          cd ..
          zip -r /tmp/lakshman_siva_repo.zip "$(basename "$GITHUB_WORKSPACE")"

      - name: Create .env File
        run: echo "$ENV_FILE_CONTENT" >> /tmp/.env

      - name: Remove carriage returns from setup.sh
        run: sed -i 's/\r$//' setup.sh

      - name: Run Setup Script
        run: |
          sudo -E sh setup.sh \
            "$APP_GROUP" "$APP_USER" "$DB_NAME" "$DEV_DB_NAME" \
            "$DB_USER" "$DB_PASSWORD" "$TEST_DB_NAME" 

      - name: Navigate to webapp directory and Run Tests
        run: |
          cd && cd ..
          cd /opt/csye6225/webapp || { echo "Webapp directory not found"; exit 1; }
          sudo -u $APP_USER npm test