name: Build Custom Image using Packer and Deploy to AWS & GCP

on:
  push:
    branches:
      - main

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest

    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DEV_DB_NAME: ${{ secrets.DEV_DB_NAME }}
      TEST_DB_NAME: ${{ secrets.TEST_DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      APP_GROUP: ${{ secrets.APP_GROUP }}
      APP_USER: ${{ secrets.APP_USER }}
      ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip the repo
        run: |
          cd ..
          zip -r /tmp/lakshman_siva_repo.zip "$(basename "$GITHUB_WORKSPACE")"

      - name: Create .env File
        run: echo "$ENV_FILE_CONTENT" >> /tmp/.env

      - name: Remove carriage returns from setup.sh
        run: sed -i 's/\r$//' setup.sh

      - name: Run Setup Script
        run: |
          sudo -E sh setup.sh \
            "$DB_NAME" "$DEV_DB_NAME" "$TEST_DB_NAME" \
            "$DB_USER" "$DB_PASSWORD" "$APP_GROUP" "$APP_USER"

      - name: Navigate to webapp directory and Run Tests
        run: |
          cd && cd ..
          cd /opt/csye6225/webapp || { echo "Webapp directory not found"; exit 1; }
          sudo -u $APP_USER npm test

      - name: Create .env File
        run: echo "$ENV_FILE_CONTENT" >> /tmp/.env

      - name: Create GCP Credentials File
        run: echo "$GCP_CREDENTIALS" >> /tmp/credentials.json

      - name: Set up Packer
        uses: hashicorp/setup-packer@v2
        with:
          version: 'latest'

      - name: Install gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'

      - name: Authenticate with Google Cloud
        run: gcloud auth activate-service-account --key-file=/tmp/credentials.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Initialize Packer
        run: packer init packer/machine-image.pkr.hcl

      - name: Build Image with Secrets
        run: |
          packer build \
            -var "gcp_project_id=${{ secrets.GCP_PROJECT_ID }}" \
            -var "machine_type=${{ vars.GCP_MACHINE_TYPE }}" \
            -var "gcp_zone=${{ vars.GCP_ZONE }}" \
            -var "disk_size=${{ vars.GCP_DISK_SIZE }}" \
            -var "disk_type=${{ vars.GCP_DISK_TYPE }}" \
            -var "gcp_network=${{ vars.GCP_NETWORK }}" \
            -var "gcp_source_image=${{ vars.GCP_SOURCE_IMAGE }}" \
            -var "gcp_source_image_family=${{ vars.GCP_SOURCE_IMAGE_FAMILY }}" \
            -var "aws_profile=${{ vars.AWS_PROFILE }}" \
            -var "aws_region=${{ vars.AWS_REGION }}" \
            -var "ssh_username=${{ vars.SSH_USERNAME }}" \
            -var "subnet_id=${{ vars.SUBNET_ID }}" \
            -var "instance_type=${{ vars.INSTANCE_TYPE }}" \
            -var "demo_account_id=${{ vars.DEMO_ACCOUNT_ID }}" \
            -var "db_name=${{ secrets.DB_NAME }}" \
            -var "dev_db_name=${{ secrets.DEV_DB_NAME }}" \
            -var "test_db_name=${{ secrets.TEST_DB_NAME }}" \
            -var "db_user=${{ secrets.DB_USER }}" \
            -var "db_password=${{ secrets.DB_PASSWORD }}" \
            -var "app_group=${{ secrets.APP_GROUP }}" \
            -var "app_user=${{ secrets.APP_USER }}" \
            packer/machine-image.pkr.hcl

      - name: Share the image with other GCP projects
        run: |
          IMAGE_NAME=$(gcloud compute images list --project ${{ secrets.GCP_PROJECT_ID }} --sort-by="~creationTimestamp" --filter="name~^csye6225-" --format="value(NAME)" | head -n1)
          gcloud compute images add-iam-policy-binding $IMAGE_NAME \
            --project ${{ secrets.GCP_PROJECT_ID }} \
            --member=serviceAccount:${{ secrets.GCP_SHARED_ACCOUNT_EMAIL }} \
            --role=roles/compute.imageUser
